import 'package:idensity_ble_client/models/meas_units/meas_unit.dart';
import 'package:idensity_ble_client/models/settings/device_mode.dart';

class MeasUnitSeed {
  static List<MeasUnit> getMeasUnits() {
    return [
      MeasUnit(        
        name: "г/см^3",
        coeff: 1,
        offset: 0,
        deviceMode: DeviceMode.density,
        measMode: 0,
        userCantDelete: true,
      ),
      MeasUnit(
        name: "кг/м^3",
        coeff: 1000,
        offset: 0,
        deviceMode: DeviceMode.density,
        measMode: 0,
        userCantDelete: true,
      ),
      MeasUnit(
        name: "г/л",
        coeff: 1000,
        offset: 0,
        deviceMode: DeviceMode.density,
        measMode: 0,
        userCantDelete: true,
      ),
      MeasUnit(
        name: "г/см^3",
        coeff: 1,
        offset: 0,
        deviceMode: DeviceMode.density,
        measMode: 1,
        userCantDelete: true,
      ),
      MeasUnit(
        name: "кг/м^3",
        coeff: 1000,
        offset: 0,
        deviceMode: DeviceMode.density,
        measMode: 1,
        userCantDelete: true,
      ),
      MeasUnit(
        name: "г/л",
        coeff: 1000,
        offset: 0,
        deviceMode: DeviceMode.density,
        measMode: 1,
        userCantDelete: true,
      ),
      MeasUnit(
        name: "г/см^3",
        coeff: 1,
        offset: 0,
        deviceMode: DeviceMode.density,
        measMode: 2,
        userCantDelete: true,
      ),
      MeasUnit(
        name: "г/л",
        coeff: 1000,
        offset: 0,
        deviceMode: DeviceMode.density,
        measMode: 2,
        userCantDelete: true,
      ),
      MeasUnit(
        name: "%",
        coeff: 1,
        offset: 0,
        deviceMode: DeviceMode.density,
        measMode: 3,
        userCantDelete: true,
      ),
      MeasUnit(
        name: "%",
        coeff: 1,
        offset: 0,
        deviceMode: DeviceMode.density,
        measMode: 4,
        userCantDelete: true,
      ),
      MeasUnit(
        name: "%",
        coeff: 1,
        offset: 0,
        deviceMode: DeviceMode.density,
        measMode: 5,
        userCantDelete: true,
      ),
      MeasUnit(
        name: "%",
        coeff: 1,
        offset: 0,
        deviceMode: DeviceMode.density,
        measMode: 6,
        userCantDelete: true,
      ),
      MeasUnit(
        name: "мм",
        coeff: 1,
        offset: 0,
        deviceMode: DeviceMode.level,
        measMode: 0,
        userCantDelete: true,
      ),
      MeasUnit(
        name: "м",
        coeff: 0.001,
        offset: 0,
        deviceMode: DeviceMode.level,
        measMode: 0,
        userCantDelete: true,
      ),
      MeasUnit(
        name: "%",
        coeff: 1,
        offset: 0,
        deviceMode: DeviceMode.level,
        measMode: 1,
        userCantDelete: true,
      ),
      MeasUnit(
        name: "м^3",
        coeff: 1,
        offset: 0,
        deviceMode: DeviceMode.level,
        measMode: 2,
        userCantDelete: true,
      ),
      MeasUnit(
        name: "см^3",
        coeff: 1000000,
        offset: 0,
        deviceMode: DeviceMode.level,
        measMode: 2,
        userCantDelete: true,
      ),
       MeasUnit(
        name: "мм/c",
        coeff: 1,
        offset: 0,
        deviceMode: DeviceMode.level,
        measMode: 3,
        userCantDelete: true,
      ),
      MeasUnit(
        name: "мм/мин",
        coeff: 0.06,
        offset: 0,
        deviceMode: DeviceMode.level,
        measMode: 3,
        userCantDelete: true,
      ),
      MeasUnit(
        name: "см/с",
        coeff: 0.1,
        offset: 0,
        deviceMode: DeviceMode.level,
        measMode: 3,
        userCantDelete: true,
      ),
      MeasUnit(
        name: "см/ч",
        coeff: 360,
        offset: 0,
        deviceMode: DeviceMode.level,
        measMode: 3,
        userCantDelete: true,
      ),
      MeasUnit(
        name: "м/ч",
        coeff: 3.6,
        offset: 0,
        deviceMode: DeviceMode.level,
        measMode: 3,
        userCantDelete: true,
      ),     

    ];
  }
}
